language: "node_js"
node_js:
  - "node"
install:
  - "npm install -g gitbook@3.2.3"
  - "npm install -g gitbook-cli@2.3.2"
branches:
  only:
    - master
env:
  global:
    - GH_REF: github.com/wenshiguo/road-dev.git
#sudo: false
script:
  - bash summary_create.sh
  - travis_wait 100 bash deploy.sh
